name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Laravel app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd /var/www
            sudo rm -rf chiswastore
            sudo git clone https://github.com/mcmuchenje/chiswastore.git
            sudo chown -R www-data:www-data chiswastore
            cd chiswastore
            sudo chmod -R 777 storage bootstrap/cache
            sudo php -r "file_exists('.env') || copy('.env.ci', '.env');"
            sudo composer install
            sudo rm -rf /etc/apache2/sites-available/httpd.conf /etc/apache2/sites-enabled/httpd.conf
            sudo cp httpd.conf /etc/apache2/sites-available/httpd.conf
            sudo ln -s /etc/apache2/sites-available/httpd.conf /etc/apache2/sites-enabled/httpd.conf
            sudo systemctl reload apache2
            sudo ../ && sudo chown -R www-data:www-data chiswastore
            echo 'Deployment successful to digital ocean'

