name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
  deploy:
    runs-on: ubuntu-latest
    needs: laravel-tests
    steps:
      - name: Deploy Laravel app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd /var/www
            sudo rm -rf chiswastore
            sudo git clone https://github.com/mcmuchenje/chiswastore.git
            cd chiswastore
            sudo cat <<EOF >.env
            APP_NAME=Laravel
            APP_ENV=local
            APP_KEY=base64:tb8AW7sZt98RVYEo0KsMOkFDWITMy4+U1TSosRacfeg=
            APP_DEBUG=true
            APP_URL=http://localhost

            LOG_CHANNEL=stack
            LOG_LEVEL=debug

            DB_CONNECTION=mysql
            DB_HOST=134.209.225.255
            DB_PORT=3306
            DB_DATABASE=test
            DB_USERNAME=paymeuser
            DB_PASSWORD=52Q9JJso2Dw1WrFIO0VK

            BROADCAST_DRIVER=log
            CACHE_DRIVER=file
            FILESYSTEM_DRIVER=local
            QUEUE_CONNECTION=sync
            SESSION_DRIVER=file
            SESSION_LIFETIME=120

            MEMCACHED_HOST=127.0.0.1

            REDIS_HOST=127.0.0.1
            REDIS_PASSWORD=null
            REDIS_PORT=6379

            MAIL_MAILER=smtp
            MAIL_HOST=mailhog
            MAIL_PORT=1025
            MAIL_USERNAME=null
            MAIL_PASSWORD=null
            MAIL_ENCRYPTION=null
            MAIL_FROM_ADDRESS=null
            MAIL_FROM_NAME="${APP_NAME}"

            AWS_ACCESS_KEY_ID=
            AWS_SECRET_ACCESS_KEY=
            AWS_DEFAULT_REGION=us-east-1
            AWS_BUCKET=
            AWS_USE_PATH_STYLE_ENDPOINT=false

            PUSHER_APP_ID=
            PUSHER_APP_KEY=
            PUSHER_APP_SECRET=
            PUSHER_APP_CLUSTER=mt1

            MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
            MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

            EOF
            sudo chown -R www-data:www-data chiswastore
            composer install
            sudo rm -rf /etc/apache2/sites-available/httpd.conf /etc/apache2/sites-enabled/httpd.conf
            sudo cp httpd.conf /etc/apache2/sites-available/httpd.conf
            sudo ln -s /etc/apache2/sites-available/httpd.conf /etc/apache2/sites-enabled/httpd.conf
            sudo systemctl reload apache2
            echo 'Deployment successful to digital ocean'

